"""Remove unique constraint

Revision ID: 5dc17a275a5d
Revises: 
Create Date: 2022-08-08 14:48:34.466618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc17a275a5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('published_record_set_reporting_period_id_key', 'published_record_set', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('published_record_set_reporting_period_id_key', 'published_record_set', ['reporting_period_id'])
    # ### end Alembic commands ###
