#load this along with either the dev or prod override files

version: "3.9"

services:

  client:
    build: client
    image: 5050.ni.bbc.co.uk:8443/5050-client-dev:latest
    dns:
      - 127.0.0.11
    networks:
      - private
    depends_on:
      - api
    deploy:
      mode: global

  api:
    build: api
    image: 5050.ni.bbc.co.uk:8443/5050-api-dev:latest
    networks:
      - private
    environment:
      - rt_db_name=rt
      - rt_db_host=db
      - rt_db_user=postgres
      - rt_debug=True
    secrets:
      - ni-app-tig.keytab
      - rt_app_account_pw
      - rt_db_pw
      - rt_secret
    depends_on:
      - db
    dns:
      - 127.0.0.11
      - 10.68.140.2 #bbc dns
    deploy:
      mode: global
      endpoint_mode: dnsrr

  db:
    image: postgres:13.6
    networks:
      - private
    environment:
      - POSTGRES_DB=rt
      - POSTGRES_PASSWORD_FILE=/run/secrets/rt_db_pw
    secrets:
      - rt_db_pw
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.postgres==true"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d rt" ]
      interval: 2s
      timeout: 2s
      retries: 20

secrets:
  rt_db_pw:
    external: true
  ni-app-tig.keytab:
    external: true
  rt_app_account_pw:
    external: true
  rt_secret:
    external: true

networks:
  private:
    driver: overlay
