version: "3.9"

services:
  haproxy:
    build:
      context: ./haproxy-config
    image: 5050.ni.bbc.co.uk:8443/5050-haproxy-dev:latest
    entrypoint:
      [
        "/usr/local/sbin/haproxy",
        "-f",
        "/etc/haproxy/haproxy.cfg",
        "-L",
        "local_haproxy"
      ]
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    dns: [ 127.0.0.11, 10.68.140.2 ]
    networks:
      - frontend
    deploy:
      mode: global
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8443
        published: 8443
        protocol: tcp
        mode: host
      - target: 9101
        published: 9101
        protocol: tcp
        mode: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./haproxy-config/config:/etc/haproxy
networks:
  frontend:
    driver: overlay
