version: "3.9"

services:
  # Python API service
  api:
    build: api
    networks:
      - private
      - frontend
    environment:
      - db_name=rt
      - db_host=db
    secrets:
      - source: db-password
        target: /run/secrets/db_pw
        mode: 0400
      - source: app-secret
        target: /run/secrets/secret
        mode: 0400
    depends_on:
      - db
      - api_init
    volumes:
      - sock:/sock

  # Python first-time API init script
  api_init:
    build: api
    networks:
      - private
    environment:
      - db_name=rt
      - db_host=db
      - RT_DUMMY_DATA=1
    secrets:
      - source: db-password
        target: /run/secrets/db_pw
        mode: 0400
      - source: app-secret
        target: /run/secrets/secret
        mode: 0400
    depends_on:
      - db
    restart: "no"
    entrypoint: [ "./docker-api-init.sh" ]

  # Typescript assets
  static:
    restart: always
    build: client
    volumes:
      - staticFiles:/www

  # nginx reverse-proxy
  nginx:
    image: nginx:1.20
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - staticFiles:/www:ro
      - sock:/sock
    ports:
      - 80:80
    networks:
      - frontend
    depends_on:
      - static
      - api

  # Postgres database
  db:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_DB=rt
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    secrets:
      - db-password
    expose:
      - 5432
    networks:
      - private

volumes:
  # Volume to share static assets from TS container to nginx
  staticFiles:
  # Sockets to communicate between containers
  sock:

secrets:
  # Database password
  db-password:
    file: ./secrets/db-password.dev
  # FastAPI app secret
  app-secret:
    file: ./secrets/app-secret.dev

networks:
  private:
  frontend:
