version: "3.9"

services:

  client:
    environment:
      - NODE_ENV=development
    networks:
      - frontend

  api:
    networks:
      - frontend
    environment:
      - rt_debug=True

  db:
    volumes:
      - /home/cobair01/5050-pgdata:/var/lib/postgresql/data

networks:
  frontend:
    driver: overlay
