version: "3.9"

services:
  client:
    image: 5050.ni.bbc.co.uk:8443/5050-client-prod:latest
    networks:
      - haproxy-network
  api:
    image: 5050.ni.bbc.co.uk:8443/5050-api-prod:latest
    environment:
      - rt_debug=False
    networks:
      - haproxy-network
  db:
    volumes:
      - /mnt/data/postgres/5050:/var/lib/postgresql/data
networks:
  haproxy-network:
    external: true
