version: "3.9"

services:

  client:
    environment:
      - NODE_ENV=development
    networks:
      - frontend
    logging:
      driver: "awslogs"
      options:
        mode: non-blocking
        awslogs-region: "eu-west-2"
        awslogs-group: "RobTestLogGroup"
        awslogs-force-flush-interval-seconds: 60
        tag: "{{.Name}}"

  api:
    networks:
      - frontend
    dns: 172.17.37.49 #needs to use wsl2 dns on bbc laptop, maybe zscaler issue 
    environment:
      - rt_debug=True
      - GUNICORN_WORKERS=1
      - TASK_SLOT={{.Task.Slot}}
    logging:
      driver: "awslogs"
      options:
        mode: non-blocking
        awslogs-region: "eu-west-2"
        awslogs-group: "RobTestLogGroup"
        awslogs-force-flush-interval-seconds: 60
        tag: "{{.Name}}"

  db:
    volumes:
      - /home/cobair01/5050-pgdata:/var/lib/postgresql/data
    logging:
      driver: "awslogs"
      options:
        mode: non-blocking
        awslogs-region: "eu-west-2"
        awslogs-group: "RobTestLogGroup"
        awslogs-force-flush-interval-seconds: 60
        tag: "{{.Name}}"

  backup:
    logging:
      driver: "awslogs"
      options:
        mode: non-blocking
        awslogs-region: "eu-west-2"
        awslogs-group: "RobTestLogGroup"
        awslogs-force-flush-interval-seconds: 60
        tag: "{{.Name}}"

networks:
  frontend:
    driver: overlay
