"""Custom column tables

Revision ID: f8ebe547d380
Revises: 
Create Date: 2021-12-22 15:54:29.656451

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users


# revision identifiers, used by Alembic.
revision = "f8ebe547d380"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_column",
        sa.Column("id", fastapi_users.db.sqlalchemy.GUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_custom_column_id"), "custom_column", ["id"], unique=False)
    op.create_table(
        "dataset_custom_column",
        sa.Column("id", fastapi_users.db.sqlalchemy.GUID(), nullable=False),
        sa.Column("dataset_id", fastapi_users.db.sqlalchemy.GUID(), nullable=True),
        sa.Column(
            "custom_column_id", fastapi_users.db.sqlalchemy.GUID(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["custom_column_id"],
            ["custom_column.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dataset_custom_column_custom_column_id"),
        "dataset_custom_column",
        ["custom_column_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dataset_custom_column_dataset_id"),
        "dataset_custom_column",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dataset_custom_column_id"),
        "dataset_custom_column",
        ["id"],
        unique=False,
    )
    op.create_table(
        "custom_column_value",
        sa.Column("id", fastapi_users.db.sqlalchemy.GUID(), nullable=False),
        sa.Column("record_id", fastapi_users.db.sqlalchemy.GUID(), nullable=True),
        sa.Column(
            "custom_column_id", fastapi_users.db.sqlalchemy.GUID(), nullable=True
        ),
        sa.Column("inputter_id", fastapi_users.db.sqlalchemy.GUID(), nullable=True),
        sa.Column("value", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["custom_column_id"],
            ["custom_column.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inputter_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["record.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_custom_column_value_custom_column_id"),
        "custom_column_value",
        ["custom_column_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_column_value_id"), "custom_column_value", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_custom_column_value_inputter_id"),
        "custom_column_value",
        ["inputter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_column_value_record_id"),
        "custom_column_value",
        ["record_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_custom_column_value_record_id"), table_name="custom_column_value"
    )
    op.drop_index(
        op.f("ix_custom_column_value_inputter_id"), table_name="custom_column_value"
    )
    op.drop_index(op.f("ix_custom_column_value_id"), table_name="custom_column_value")
    op.drop_index(
        op.f("ix_custom_column_value_custom_column_id"),
        table_name="custom_column_value",
    )
    op.drop_table("custom_column_value")
    op.drop_index(
        op.f("ix_dataset_custom_column_id"), table_name="dataset_custom_column"
    )
    op.drop_index(
        op.f("ix_dataset_custom_column_dataset_id"), table_name="dataset_custom_column"
    )
    op.drop_index(
        op.f("ix_dataset_custom_column_custom_column_id"),
        table_name="dataset_custom_column",
    )
    op.drop_table("dataset_custom_column")
    op.drop_index(op.f("ix_custom_column_id"), table_name="custom_column")
    op.drop_table("custom_column")
    # ### end Alembic commands ###
