[sheets]
ids = [
    "155JtrPzvJ9iDI_Pr2URM-znXq6YlBBF2RBM1cqBjdH0"
]
has_header = true

[columns]
publish_date = "A"
program_name = "B"
program_id = "O"
episode = "C"
sub_episode = "D"
guest = "F"
categories = { race = ["G", "H"], gender = ["I", "J"], sexual_orientation = ["K", "L"] }
