name: Python

on:
  push:
    branches: [main]
    paths: [api/**]
  pull_request:
    branches: [main]
    paths: [api/**]

jobs:
  build:
    name: Test Python
    runs-on: ubuntu-latest
    env:
      wd: ./api
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        id: python

      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}

      - name: Cache requirements
        id: cache-reqs
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Get requirements
        working-directory: ${{env.wd}}
        run: |
          python -m pip install -r requirements.txt

      - name: Test
        working-directory: ${{env.wd}}
        run: python -m unittest -v *_test.py
